#!/bin/bash
# Uesage 
#	./sync # 同步
#	./sync clean # 清理目标目录 

set -e

COMMAND=$1

EXECDIR=$2

usage(){
	echo "Usage: $0 [clean] | [help] "
	echo ""
	echo "The most commonly used commands are:"
	echo "    clean			delete all files in TARGET_DIR"
	echo "    help			display this help and exit"
	echo "    include|in			only rsync include dir"
	echo "    exclude|ex			rsync other dirs except exclude dir"
	exit 1
}

# BRANCH_NAME=`git status | head -1 | cut -d " " -f 3`
# BRANCH_STATUS=`git status | tail -1 | cut -d " " -f 6`

# 检查分支及状态

# if [ $BRANCH_NAME = "master" ]
# then
# 	echo "on branch master"
# else
# 	echo "not on branch master"
# 	exit 0
# fi

# if [ $BRANCH_STATUS = "clean" ]
# then
# 	echo "working tree clean"
# else
# 	echo "working tree not clean"
# 	exit 0
# fi

# config 应该所有人统一内容，所以直接覆盖
# cp config_dev/ config/
# chmod -R 755 runtime
# rm -rf runtime/*

PHPUNIT_TARGET_DIR=swoft
SSH_USERNAME=jiachunhui

TARGET_DIR=swoft
USERNAME=ailab
TARGET_HOST=192.168.1.192


echo $USERNAME@$TARGET_HOST::$TARGET_DIR

RSYNC_DESTINATION=$USERNAME@$TARGET_HOST::$TARGET_DIR


echo $COMMAND

EXECCOMMAND=''


IS_PHPUNIT=0
IS_DELETE=0
case $COMMAND in
"help"|"h")
	usage
	exit 1
	;;
"test")
	IS_PHPUNIT=1
	;;
"clean")
	IS_DELETE=1

	echo "[`date +"%F %T"`] del start"
	ssh $USERNAME@$TARGET_HOST "cd $TARGET_DIR/ && rm * -rf"
	echo "[`date +"%F %T"`] del is complete!"

	exit 0
	;;
"include"|"exclude"|"in"|"ex")
	EXECCOMMAND=$COMMAND
	;;
esac

rsync_delete="u"
rsync_include=""

rsync_exclude=" --exclude=.settings/ --exclude=bin-debug/ --exclude=.idea --exclude=deploy/ --exclude=sync  --exclude=.svn --exclude=.git --exclude=.github --exclude=.metadata --exclude=app.data.mk* --exclude=sync_settings* --exclude=.project --exclude=.buildpath --exclude=.DS_Store --exclude=.travis.yml --exclude=runtime/ --exclude=.gitignore --exclude=composer.lock --exclude=.build.sand.mk/"

if [ -z "$EXECCOMMAND" ]; then
    echo ""
elif [ "$EXECCOMMAND" == "include" ];then
	rsync_exclude=" --exclude=/* $rsync_exclude " # 最重要 /* 
	rsync_include=" --include=$EXECDIR "
elif [ "$EXECCOMMAND" == "exclude" ];then
	rsync_exclude="$rsync_exclude --exclude=$EXECDIR "
elif [ "$EXECCOMMAND" == "in" ];then
	rsync_exclude=" --exclude=/* $rsync_exclude " # 最重要 /* 
	rsync_include=" --include=$EXECDIR "
elif [ "$EXECCOMMAND" == "ex" ];then
	rsync_exclude="$rsync_exclude --exclude=$EXECDIR "
fi

# echo $rsync_include 
# echo $rsync_exclude
# exit 0

echo "[`date +"%F %T"`] Syncing files to remote destination... $RSYNC_DESTINATION/"
F:/bin/cwRsync/bin/rsync.exe -vrltczO$rsync_delete  --chmod=a+rx,u+rwx,g+rx $rsync_include $rsync_exclude ./ $RSYNC_DESTINATION/
echo "[`date +"%F %T"`] Syncing is complete!"



if [ "$IS_PHPUNIT" == 1 ]
then
	# if [ "$2" ]
	# then
	# 	PHPUNIT_ITEM="units/$2"
	# else
	# 	PHPUNIT_ITEM="--testsuite AllTests"
	# fi
	msg "=============  phpunit  ==============="
	echo "[`date +"%F %T"`] PHPUNIT start"
	ssh $SSH_USERNAME@$TARGET_HOST "cd $PHPUNIT_TARGET_DIR/test/ && phpunit "
	echo "[`date +"%F %T"`] PHPUNIT is complete!"
	exit 0;
fi
